### ISSUE TITLE
调整组件加载样式的策略以适应babel-plugin-import

### ISSUE THREAD

**Issue by Tan90Qian** [mcfed/components#4]
babel-plugin-import通过config的`style`字段来表明分包后组件应该从哪个文件加载样式，由于tsc的编译不像webpack与rollup那样会通过loader将样式打包进js文件，因此需要从以下两种策略中选择一种：
1. 保持现有逻辑，要求使用了该库的下游项目配置与该项目一致的loader（如less-loader）
2. 组件中不直接引用样式文件，并将样式文件安置于固定目录、固定文件下，如
   - 源文件为`./style/index.less`，并提供`./style/index.ts`文件作为插件分块加载样式的入口
   - 使用工具将所有目录下的`./style/index.less`编译成对应的css版本，降低对下游项目的使用要求
   - 使用工具将所有目录下的`./style/index.less`与`./style/index.css`文件分别收集到umd打包目录下，作为`${包名}.less`与`${包名}.css`文件保存

在这种改造完成后，下游项目将可以使用与antd相同的方式引入样式文件

**Comment by Tan90Qian** [comment]
调整了样式加载策略后，当components包的组件之间存在引用组件引用关系时，需要在引入方组件的style/index.js文件中加入对被引用方组件的样式入口的依赖 @Jshoes

**Comment by Jshoes** [comment]
has finished
